[build]
  publish = "site/blog/_site"
  command = "pnpm -F blog run build"

[[plugins]]
  package = "netlify-plugin-webmentions"
  [plugins.inputs]
    baseUrl = "https://blog.andrewshell.org"
    feedPath = "/rss.xml"
    limit = 1

[[plugins]]
  package = "@andrewshell/netlify-plugin-rsscloud"
  [plugins.inputs]
    feedUrl = "https://blog.andrewshell.org/rss.xml"
    pingUrl = "https://rpc.rsscloud.io/ping"

[[headers]]
  for = "/.well-known/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
